name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # كل يوم 12 منتصف الليل UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

       - name: Generate contribution graph
        uses: lowlighter/metrics@latest
        with:
          filename: output/pacman-contribution-graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_type: pacman
          plugin_calendar_days: 365
          plugin_calendar_limit: 0
          plugin_calendar_sections: yes
